kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: customer-simple
spec:
  to:
    kind: Service
    name: customer-simple
  port:
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: customer-simple
  labels:
    app: customer-simple
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: customer-simple
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-simple
  labels:
    app: customer-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-simple
  template:
    metadata:
      labels:
        app: customer-simple
    spec:
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/base-data/customer-simple
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: app
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: promethus
              protocol: TCP
          env:
          - name: TZ
            value: "Asia/Shanghai"
          - name: LANG
            value: en_US.UTF-8
          - name: JAVA_OPTS
            value: "-Dfile.encoding=UTF8"
          - name: AB_JOLOKIA_AUTH_OPENSHIFT
            value: 'true'
          - name: AB_JOLOKIA_OPTS
            value: 'useSslClientAuthentication=false,protocol=https'
          - name: 'AB_JOLOKIA_PASSWORD_RANDOM'
            value: 'false'
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          volumeMounts:
          - name: data-volume
            mountPath: /deployments/data
      volumes:
      - name: data-volume
        configMap:
          name: customer-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-data
data:
  data.json: |
    [
        {
            "id": "202292",
            "name": "MEDITRADING",
            "factory": "1000"
        },
        {
            "id": "60093633",
            "name": "西安市秦星医疗设备有限公司",
            "factory": "1000"
        },
        {
            "id": "101770",
            "name": "广州市执康医疗设备有限公司",
            "factory": "1008"
        },
        {
            "id": "60121360",
            "name": "天津云驰嘉科技发展有限公司",
            "factory": "1008"
        }
    ]
